
'use server';

/**
 * @fileOverview Diagnoses crop diseases from uploaded leaf images and provides treatment advice.
 *
 * - diagnoseCropDisease - A function that handles the crop disease diagnosis process.
 * - DiagnoseCropDiseaseInput - The input type for the diagnoseCropDisease function.
 * - DiagnoseCropDiseaseOutput - The return type for the diagnoseCropDisease function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DiagnoseCropDiseaseInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a diseased plant leaf, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type DiagnoseCropDiseaseInput = z.infer<typeof DiagnoseCropDiseaseInputSchema>;

const DiagnoseCropDiseaseOutputSchema = z.object({
  diseaseName: z.string().describe('The name of the identified disease.'),
  description: z.string().describe('A detailed description of the disease, its symptoms, and causes.'),
  diseaseStage: z.string().describe('The likely stage of the disease (e.g., Early, Mid, Advanced).'),
  remedyType: z.string().describe('The type of remedy suggested (e.g., Fungicide, Pesticide, Cultural Practice).'),
  suggestedRemedy: z.string().describe('A detailed suggested remedy and treatment plan for the disease.'),
});
export type DiagnoseCropDiseaseOutput = z.infer<typeof DiagnoseCropDiseaseOutputSchema>;

export async function diagnoseCropDisease(input: DiagnoseCropDiseaseInput): Promise<DiagnoseCropDiseaseOutput> {
  return diagnoseCropDiseaseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'diagnoseCropDiseasePrompt',
  input: {schema: DiagnoseCropDiseaseInputSchema},
  output: {schema: DiagnoseCropDiseaseOutputSchema},
  prompt: `You are an expert in plant pathology, skilled in diagnosing crop diseases from leaf images. Analyze the provided image and identify the disease.

  Photo: {{media url=photoDataUri}}
  
  Provide a comprehensive diagnosis including:
  - The disease name.
  - A detailed description of the disease, its common symptoms, and what might cause it.
  - The likely stage of the disease (e.g., Early, Mid, Advanced).
  - The type of remedy required (e.g., Fungicide, Pesticide, Cultural Practice, Nutrient Management).
  - A detailed step-by-step suggested remedy and treatment plan for the farmer.`,
});

const diagnoseCropDiseaseFlow = ai.defineFlow(
  {
    name: 'diagnoseCropDiseaseFlow',
    inputSchema: DiagnoseCropDiseaseInputSchema,
    outputSchema: DiagnoseCropDiseaseOutputSchema,
  },
  async input => {
    try {
      const {output} = await prompt(input);
      if (!output) {
        throw new Error("No output was generated by the AI model.");
      }
      return output;
    } catch (error) {
       console.error("Error in diagnoseCropDiseaseFlow:", error);
       // Re-throw a more user-friendly error to be caught by the frontend.
       throw new Error("The AI model is currently unavailable or experiencing high load. Please try again in a few moments.");
    }
  }
);
